### ISSUE TITLE
Default log file

### ISSUE THREAD

**Issue by viniciuszago** [fidelisrafael/nifty_services#2]
Why do not set a default log in `log/deafult.log`?

**Comment by fidelisrafael** [comment]
Currently default logger is `/dev/null` cuz `nifty_services` by itself don't log anything....
So if user want to log something, setup is need, so I dont see a gain creating a empty file if user dont need it. Right?

**Comment by viniciuszago** [comment]
I got it, but how less config I have, better it is. Have you think about interactive install to initialize with this configs?

And if I forget to config my log, I will never se what could happened 😄

**Comment by fidelisrafael** [comment]
Not at all! It's a very simple one line configuration, if user want to configure a default logger such you suggest, could simple use: `NiftyServices.config.logger = Logger.new('log/default.log)`, so if this come by default can be a inconvenient problem, since most of users don't need (and even dont want).... and if user want, it's very simple to setup this, don't you think?

**Comment by viniciuszago** [comment]
I know it's simple, but think about the future, if it comes with a lot of configs and other stuff, an interactive installer like `rake install nifty_services` would be great. 

What do you suggest to have in this case?

**Comment by fidelisrafael** [comment]
@viniciuszago Can be a option for future versions! Thanks for your interest!
